%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Marvin\Dropbox\01 Studium\III WiSe 17 18\01 Projektarbeit\Messungen\2017_09_22\2017_09_22.xls
%    Worksheet: 03
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2017/09/22 14:16:57

clearvars;
%% Import the data
[~, ~, raw] = xlsread('C:\Users\Marvin\Desktop\Projektarbeit\gondola\doc\Measurement_Matlab\2017_09_22\2017_09_22.xls','03');
raw = raw(4:end,1:2);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Length = data(:,1);
Meas = data(:,2);
% The correction from Sheet 01 were applied
ErrCorr = Length - Meas;

%% Clear temporary variables
clearvars data raw;
close all;

%% Just plot the err over the length to show the small error
figure;
hold on;
plot(Length, ErrCorr, 'gx');
title("Error against input length with an initial offset");
xlabel("Input length [mm]");
ylabel("Error [mm]");
legend("Error with quadratic correction", 'Location' ,'best');

