%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Marvin\Dropbox\01 Studium\III WiSe 17 18\01 Projektarbeit\Messungen\2017_09_22\2017_09_22.xls
%    Worksheet: 04
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2017/09/22 14:36:41

clearvars;
%% Import the data
[~, ~, raw] = xlsread('C:\Users\Marvin\Desktop\Projektarbeit\gondola\doc\Measurement_Matlab\2017_09_22\2017_09_22.xls','04');
raw = raw(3:42,2:5);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
X = data(:,1);
Y = data(:,2);
MeasX = data(:,3);
MeasY = data(:,4);
OffsetX = 2364;
OffsetY = 1200;
Anchor1X = 0;
Anchor1Y = 0;
Anchor2X = 0;
Anchor2Y = 3236;
CalibrationPointX = 400;
CalibrationPointY = 1500;
SpooledOffset1 = 1025;
SpooledOffset2 = 4353;

%% Computations
DistX = - MeasX(:) + OffsetX;
DistY = MeasY(:) - OffsetY;
ErrX = DistX(:) - X(:);
ErrY = DistY(:) - Y(:);
ErrEuclid = sqrt(ErrX.^2 + ErrY.^2);
%% Clear temporary variables
clearvars data raw;

%% Import the data
[~, ~, raw] = xlsread('C:\Users\Marvin\Desktop\Projektarbeit\gondola\doc\Measurement_Matlab\2017_09_21\2017_09_21.xls','01');
raw = raw(3:42,1:5);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Punkt = data(:,1);
MeasXOld = data(:,4);
MeasYOld = data(:,5);
%OffsetX = 2364;
%OffsetY = 1200;
%Anchor1X = 0;
%Anchor1Y = 0;
%Anchor2X = 0;
%Anchor2Y = 3236;
%CalibrationPointX = 400;
%CalibrationPointY = 1500;

%% Clear temporary variables
clearvars data raw;

%% Computations
DistXOld = - MeasXOld(:) + OffsetX;
DistYOld = MeasYOld(:) - OffsetY;
ErrXOld = DistXOld(:) - X(:);
ErrYOld = DistYOld(:) - Y(:);
ErrEuclidOld = sqrt(ErrXOld.^2 + ErrYOld.^2);


%% Heatmap
f = figure;
set(f, 'Units', 'normalized', 'Position', [0.2, 0.2, 0.6, 0.4]); 
hold on;
title("Accuracy in 2D with start at (x=400/y=1500)");
set(gca,'YDir','reverse');      % reverse direction of y axis
plot(Y, X, 'b.');
plot(DistY, DistX, 'g.');
plot(DistYOld, DistXOld, 'r.');
h = plot(CalibrationPointY, CalibrationPointX, 'go');
set(h, 'linewidth', 1.5);
h = plot([Anchor1Y Anchor2Y], [Anchor1X Anchor2X], 'ko');
set(h, 'linewidth', 1.5);
legend("Input", "Corrected Output", "Output", "Calibration Point", "Motor", 'Location' ,'best');
xlim([0 3236]);
ylim([0 2364]);
xlabel("Y Direction [mm]");
ylabel("X Direction [mm]");


%% Euclidean error system - compared
f = figure;
set(f, 'Units', 'normalized', 'Position', [0.2, 0.2, 0.6, 0.4]); 
hold on;
h = plot(ErrEuclid, 'gx');
set(h, 'linewidth', 1.5);
h = plot(ErrEuclidOld, 'rx');
set(h, 'linewidth', 1.5);
grid on;
title("Eucliden error in 2D");
xlabel("Measurement [mm]");
ylabel("Euclidean error [mm]");
legend("With correction", "Without correction", 'Location' ,'best');

